---
--- Generated by Luanalysis
--- Created by nori.
--- DateTime: 11/30/21 12:12 PM
---

--Grundgerüst
-- Eigene Funktionen

function grundgeruest()
    local _, polynomText = polynom1(0)

    print("Grundgerüst: Polynom 1 mit den Zahlen 0 bis 20")
    print("Polynom 1: y=" .. polynomText)
    for i = 0, 20 do
        print("x= " .. i, " y= " .. polynom1(i))
    end
    print("Ende Grundgerüst\n\n\n")
end

function polynom1 (x)
    return (x - 1) * (x + 2) * (x + 3), "(x - 1) * (x + 2) * (x + 3)"
end


--Modifikationen

--Funktionen
function polynom2 (x)
    return (x + 1) * (x - 2) * (x - 3), "(x + 1) * (x - 2) * (x - 3)"
end

function rekursion (x)
    if (x > 0) then
        print("x= " .. x, " y= " .. polynom1(x))
        x = x - 1
        return rekursion(x)
    else
        print("x= " .. x, " y= " .. polynom1(x))
        return
    end
end

function schleifen1()
    local result, polynomText = polynom1(0)

    print("Schleife 1: Summe von y= ".. polynomText .." mit 0 bis 20")

    local counter = 0

    while counter < 20 do
        result = polynom1(counter)
        counter = counter + 1
    end

    print("Ergebnis: " .. result)
    print("Ende Schleife 1\n\n\n")
end

function neueFunktion()
    local _, polynomText = polynom2(0)

    print("Neue Funktion: Polynom 2 mit den Zahlen 0 bis 20")
    print("Polynom 2: " .. polynomText)

    for i = 0, 20 do
        print("x= " .. i, " y= " .. polynom2(i))
    end

    print("Ende neue Funktion\n\n\n")
end

function schleifen2()
    local result, polynomText = polynom2(0)
    print("Schleifen 2: Ergebnisse y= ".. polynomText .. "summiert mit anderer Schleife")
    for i = 0, 20 do
        result = polynom2(i)
    end
    print("Ergebnis: " .. result)
    print("Ende Mod 3\n\n\n")

end

function nullstellen()
    local result, polynomText = polynom1(0)

    print("Nullstellen: Nullstellen Polynom 1")
    print("Polynom 1: y= ".. polynomText)

    local counter = 0

    for i = 0, 20 do
        result = polynom1(i)
        if result == 0 then
            counter = counter + 1
        end
    end

    print("Es wurden " .. counter .. " Nullstellen gefunden")
    print("Ende Mod 4\n\n\n")
end

function rekursionVerwendung()
    local _, polynomText = polynom1(0)
    print("Rekursion: Rekursive Lösung der Funktion y= ".. polynomText .." Zahlen 20 bis 0")
    rekursion(20)
end
