---
--- Generated by Luanalysis
--- Created by nori.
--- DateTime: 11/30/21 12:38 PM
---

require("grundlegendes")
require("userInput")
require("adventOfLua")

repeat
    print("Willkommen zum Zeichenbrett");
    print("Deine Optionen sind:");
    print("0 - Programm beenden")
    print("1 - Grundlegendes");
    print("2 - User Input");
    print("3 - AdventofLua");
    io.write("Your choice: ");
    local wahl = inputAufforderung()

    if wahl == 1 then
        print("Aufgabe Grundlegendes")
        grundgeruest()
        schleifen1()
        neueFunktion()
        schleifen2()
        nullstellen()
        rekursionVerwendung()

    elseif wahl == 2 then

        print("\n\n\nAufgabe User Input")
        menu()
    elseif wahl == 3 then
        tag1()
    end
    print("\n\n\n")
until wahl == 0